# Generated by Django 3.1.3 on 2021-11-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='publishedAt',
            field=models.CharField(max_length=100),
        ),
    ]
