# Generated by Django 3.2.9 on 2021-11-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20211119_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='publishedAt',
            field=models.CharField(max_length=200),
        ),
    ]
